apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-validation-job
  namespace: platine-traitement
spec:
  flinkVersion: v1_20
  image: flink:1.20-scala_2.12-java17
  imagePullPolicy: IfNotPresent
  serviceAccount: flink
  
  flinkConfiguration:
    state.checkpoints.dir: file:///opt/flink/checkpoints
    taskmanager.numberOfTaskSlots: "2"
    
  jobManager:
    resource:
      cpu: 0.5
      memory: "1024m"
      
  taskManager:
    resource:
      cpu: 0.5
      memory: "1024m"
      
  job:
    jarURI: local:///opt/flink/opt/flink-python_2.12-1.20.1.jar
    entryClass: org.apache.flink.client.python.PythonDriver
    args:
      - -pyclientexec
      - /opt/flink/python-venv/bin/python3
      - -py
      - /opt/flink/scripts/validation_job.py
    parallelism: 1
    upgradeMode: stateless

  podTemplate:
    spec:
      volumes:
        - name: python-venv-volume
          emptyDir: {}
        - name: flink-usrlib
          emptyDir: {}
        - name: pyflink-scripts
          configMap:
            name: flink-pyflink-scripts

      initContainers:
        - name: pyflink-bootstrap
          image: flink:1.20-scala_2.12-java17
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -ex
              apt-get update
              apt-get install -y --no-install-recommends python3 python3-pip python3-venv
              python3 -m venv /opt/flink/python-venv
              /opt/flink/python-venv/bin/pip install --no-cache-dir apache-flink==1.20.1 kafka-python-ng
              chmod -R 777 /opt/flink/python-venv
          volumeMounts:
            - name: python-venv-volume
              mountPath: /opt/flink/python-venv

      containers:
        - name: flink-main-container
          volumeMounts:
            - name: python-venv-volume
              mountPath: /opt/flink/python-venv
            - name: pyflink-scripts
              mountPath: /opt/flink/scripts
