apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-validation-job
  namespace: platine-traitement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-validation-job
  template:
    metadata:
      labels:
        app: flink-validation-job
    spec:
      containers:
      - name: validator
        image: python:3.10-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install kafka-python-ng && python /app/validation.py
        volumeMounts:
        - name: script-vol
          mountPath: /app
      volumes:
      - name: script-vol
        configMap:
          name: stream-processing-scripts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-enrichment-job
  namespace: platine-traitement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-enrichment-job
  template:
    metadata:
      labels:
        app: flink-enrichment-job
    spec:
      containers:
      - name: enricher
        image: python:3.10-slim
        command: ["/bin/sh", "-c"]
        args:
          - pip install kafka-python-ng && python /app/enrichment.py
        volumeMounts:
        - name: script-vol
          mountPath: /app
      volumes:
      - name: script-vol
        configMap:
          name: stream-processing-scripts